Repository fairlearn/fairlearn, pull requests merged in 2019-11, with the labels that each got.

#141 README update for v0.3.0 release
  CONTRIBUTING.md
  README.md
Labels: documentation

#145 tempeh upgrade to v0.1.7 to fix notebooks in python 3.5
  devops/notebook-job-template.yml
  requirements-fixed.txt
  requirements.txt
Labels: bug

#146 polish and fix contributing.md
  CONTRIBUTING.md
Labels: enhancement

#152 Postprocessing documentation updates
  fairlearn/postprocessing/__init__.py
  fairlearn/postprocessing/_constants.py
  fairlearn/postprocessing/_curve_plotting_utilities.py
  fairlearn/postprocessing/_interpolated_prediction.py
  fairlearn/postprocessing/_postprocessing.py
  fairlearn/postprocessing/_roc_curve_utilities.py
  fairlearn/postprocessing/_threshold_operation.py
  fairlearn/postprocessing/_threshold_optimizer.py
  fairlearn/reductions/__init__.py
  notebooks/Threshold Optimization Postprocessing for Binary Classification on COMPAS dataset.ipynb
  test/unit/postprocessing/test_curve_utilities.py
  test/unit/postprocessing/test_threshold_optimization.py
  test/unit/postprocessing/test_utilities.py
Labels: documentation

#149 Add authors page
  AUTHORS.md
  CODEOWNERS.md
  README.md
Labels: documentation

#151 Exponentiated Gradient documentation updates
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_grid_search/grid_search.py
Labels: documentation

#154 Bugfix for _Lagrangian
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
Labels: bug

#155 tempeh v0.1.8
  fairlearn/postprocessing/_threshold_optimizer.py
  notebooks/Binary Classification on COMPAS dataset.ipynb
  requirements-fixed.txt
  requirements.txt
  test/perf/test_performance.py
Labels: enhancement

#158 Single element fix for group metrics
  fairlearn/metrics/_balanced_root_mean_squared_error.py
  fairlearn/metrics/_input_manipulations.py
  fairlearn/metrics/_mean_predictions.py
  fairlearn/metrics/_metrics_engine.py
  test/unit/metrics/test_group_sklearn_wrappers.py
  test/unit/metrics/test_input_manipulations.py
  test/unit/metrics/test_mean_predictions.py
  test/unit/metrics/test_metrics_engine.py
Labels: bug

#160 Initial Pipeline for PyPI releases
  devops/create-wheel-step-template.yml
  devops/fetch-version-from-artifacts-steps-template.yml
  devops/notebook-pypi-job-template.yml
  devops/prepare-repo-for-pip-testing-steps-template.yml
  devops/pypi-deployment-stages-template.yml
  devops/pypi-release.yml
  devops/unit-tests-pypi-job-template.yml
  fairlearn/__init__.py
  scripts/build-wheels.ps1
  scripts/fairlearn_version.py
  scripts/set-variable-from-file.ps1
Labels: enhancement
