Repository fairlearn/fairlearn, pull requests merged in 2019-10, with the labels that each got.

#45 Restructure Exponentiated Gradient into a class with the new API
  fairlearn/reductions/__init__.py
  fairlearn/reductions/exponentiated_gradient/_constants.py
  fairlearn/reductions/exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/exponentiated_gradient/exponentiated_gradient.py
  test/reductions/exponentiated_gradient/__init__.py
  test/reductions/exponentiated_gradient/test_expgrad_smoke.py
  test/reductions/exponentiated_gradient/test_utilities.py
Labels: enhancement

#59 add BGL and basis handling in moments
  fairlearn/reductions/moments/bounded_group_loss.py
  fairlearn/reductions/moments/conditional_opportunity.py
  fairlearn/reductions/moments/moment.py
Labels: enhancement

#94 Add a comment to pipeline YAMLs
  devops/code-coverage.yml
  devops/nightly.yml
Labels: enhancement

#98 Build tidying
  devops/PR-Gate.yml
  devops/code-coverage.yml
  devops/nightly.yml
  devops/schedule-test.yml
Labels: enhancement

#100 Sphinx onboarding
  .gitignore
  docs/conf.py
  docs/index.rst
  fairlearn/metrics/__init__.py
  fairlearn/metrics/metrics_engine.py
  fairlearn/reductions/grid_search/grid_search.py
  requirements.txt
Labels: enhancement

#108 Move exponentiated gradient logic into class and reformat existing documentation
  fairlearn/reductions/exponentiated_gradient/exponentiated_gradient.py
Labels: documentation, enhancement

#119 COMPAS dataset for notebooks - post processing
  notebooks/Threshold Optimization Post-Processing for Binary Classification.ipynb
  notebooks/Threshold Optimization Postprocessing for Binary Classification on COMPAS dataset.ipynb
  requirements-fixed.txt
  requirements.txt
Labels: documentation, enhancement

#130 Developer Certificate of Origin and Code of Conduct updates
  CONTRIBUTING.md
Labels: documentation
