Repository fairlearn/fairlearn, pull requests merged in 2020-08, with the labels that each got.

#532 remove datasets module usage until it is part of a released version
  docs/quickstart.rst
  examples/notebooks/plot_grid_search_census.py
Labels: bug, documentation

#535 Split up requirements file
  .circleci/config.yml
  devops/README.md
  devops/templates/requirements-installation-steps-template.yml
  devops/templates/test-run-step-template.yml
  docs/contributor_guide/development_process.rst
  requirements-customplots.txt
  requirements-dev.txt
  requirements.txt
  scripts/install_requirements.py
  scripts/requirements_override.py
  scripts/requirements_pin.py
  setup.py
Labels: dependencies

#442 Exponentiated gradient implementation for bounded group loss
  .DS_Store
  docs/user_guide/mitigation.rst
  fairlearn/reductions/__init__.py
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_moments/bounded_group_loss.py
  fairlearn/reductions/_moments/utility_parity.py
  notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/exponentiated_gradient/test_lagrangian.py
  test/unit/reductions/exponentiated_gradient/test_utilities.py
Labels: documentation, enhancement
