Repository fairlearn/fairlearn, pull requests merged in 2020-02, with the labels that each got.

#288 multiple sensitive features - postprocessing
  fairlearn/_input_validation.py
  fairlearn/postprocessing/_threshold_optimizer.py
  test/unit/constants.py
  test/unit/input_convertors.py
  test/unit/postprocessing/conftest.py
  test/unit/postprocessing/test_curve_utilities.py
  test/unit/postprocessing/test_threshold_optimization.py
Labels: enhancement, feature-request

#280 Support for multiple sensitive features
  fairlearn/_input_validation.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_grid_search/grid_search.py
  test/unit/conftest.py
  test/unit/postprocessing/conftest.py
  test/unit/postprocessing/test_utilities.py
  test/unit/reductions/conftest.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
  test/unit/reductions/grid_search/test_grid_search_demographicparity.py
  test/unit/reductions/grid_search/test_grid_search_regression.py
Labels: enhancement

#295 Fix Windows notebook tests for python 3.5 & 3.6 build by adding special case for BGL test case back
  requirements.txt
  test/notebooks/test_notebooks.py
  test/unit/reductions/grid_search/test_grid_search_regression.py
Labels: bug

#304 FIX ThresholdOptimizer: move validations to fit
  CHANGES.md
  fairlearn/postprocessing/_threshold_optimizer.py
  test/unit/postprocessing/test_threshold_optimization.py
Labels: enhancement

#289 Separate plotting code out of ThresholdOptimizer into functions
  CHANGES.md
  fairlearn/postprocessing/__init__.py
  fairlearn/postprocessing/_curve_plotting_utilities.py
  fairlearn/postprocessing/_plotting.py
  fairlearn/postprocessing/_threshold_optimizer.py
  notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
  requirements.txt
  setup.py
  test/install/test_no_matplotlib.py
  test/unit/postprocessing/conftest.py
  test/unit/postprocessing/test_plots.py
  test/unit/postprocessing/test_threshold_optimization.py
Labels: ease-of-use, enhancement, feature-request
