Repository fairlearn/fairlearn, pull requests merged in 2020-05, with the labels that each got.

#383 Add grid offset to grid generator for grid search
  fairlearn/reductions/_grid_search/_grid_generator.py
  fairlearn/reductions/_grid_search/grid_search.py
  test/unit/reductions/grid_search/test_grid_generator.py
  test/unit/reductions/grid_search/test_grid_search_demographicparity.py
Labels: enhancement

#408 update CHANGES.md with updates on moments
  CHANGES.md
Labels: documentation

#409 Convert terminology & contribution guides into generated docs on the webpage
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  TERMINOLOGY.md
  docs/README.md
  docs/conf.py
  docs/contribution_guide.rst
  docs/user_guide/fairness_in_machine_learning.rst
  docs/user_guide/mitigation.rst
  examples/README.rst
  requirements.txt
Labels: documentation

#411 Website/documentation: add initial quickstart page with installation, refine contribution guide
  .circleci/artifact_path
  README.md
  docs/api_reference/index.rst
  docs/community.rst
  docs/community/developer_call_notes/2020_05_07.rst
  docs/community/developer_call_notes/index.rst
  docs/community/index.rst
  docs/conf.py
  docs/contribution_guide.rst
  docs/contributor_guide/contributing_code.rst
  docs/contributor_guide/contributing_example_notebooks.rst
  docs/contributor_guide/development_process.rst
  docs/contributor_guide/fairlearn_proposals.rst
  docs/contributor_guide/fairlearn_repository_overview.rst
  docs/contributor_guide/index.rst
  docs/contributor_guide/ways_to_contribute.rst
  docs/index.rst
  docs/quickstart.rst
  docs/user_guide/assessment.rst
  docs/user_guide/dashboard.rst
  docs/user_guide/exponentiated_gradient.rst
  docs/user_guide/grid_search.rst
  docs/user_guide/index.rst
  docs/user_guide/metrics.rst
  docs/user_guide/mitigation.rst
  docs/user_guide/postprocessing.rst
  docs/user_guide/reductions.rst
  examples/notebooks/README.rst
  examples/notebooks/plot_binary_classification_COMPAS.py
  examples/quickstart/README.rst
  examples/quickstart/plot_adult_dataset.py
  img/fairlearn-dashboard-comparison.png
  img/fairlearn-dashboard-disparity-performance.png
  img/fairlearn-dashboard-disparity-predictions.png
  img/fairlearn-dashboard-performance.png
  img/fairlearn-dashboard-sensitive-features.png
  img/fairlearn-dashboard-start.png
Labels: documentation

#421 disable doc push temporarily
  .circleci/config.yml
Labels: documentation

#423 Replace dashboard screenshots with updated ones
  docs/user_guide/assessment.rst
  img/fairlearn-dashboard-config.png
  img/fairlearn-dashboard-disparity-performance-multiple-sensitive-features.png
  img/fairlearn-dashboard-disparity-predictions-multiple-sensitive-features.png
  img/fairlearn-dashboard-models.png
  img/fairlearn-dashboard-multiple-sensitive-features.png
  img/fairlearn-dashboard-performance-multiple-sensitive-features.png
  img/fairlearn-dashboard-results.png
Labels: documentation

#422 notes from first developer call
  docs/community/developer_call_notes/2020_05_07.rst
Labels: documentation

#386 Conform to naming conventions for attributes
  CHANGES.md
  fairlearn/__init__.py
  fairlearn/reductions/_exponentiated_gradient/_constants.py
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_grid_search/grid_search.py
  notebooks/Binary Classification with the UCI Credit-card Default Dataset.ipynb
  notebooks/Grid Search for Binary Classification.ipynb
  notebooks/Grid Search with Census Data.ipynb
  notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
  test/notebooks/test_notebooks.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
  test/unit/reductions/grid_search/test_grid_search_demographicparity.py
  test/unit/reductions/grid_search/test_grid_search_regression.py
  test/unit/reductions/grid_search/utilities.py
Labels: enhancement

#428 Reintegrate landing page into sphinx-generated documentation
  .circleci/config.yml
  docs/_static/css/landing_page_style.css
  docs/_static/fonts/TypeType-TTCommonsBold.otf
  docs/_static/fonts/TypeType-TTCommonsBold.woff
  docs/_static/fonts/TypeType-TTCommonsMedium.otf
  docs/_static/fonts/TypeType-TTCommonsMedium.woff
  docs/_static/fonts/TypeType-TTCommonsRegular.otf
  docs/_static/fonts/TypeType-TTCommonsRegular.woff
  docs/_static/images/check-icon.png
  docs/_static/images/fairlearn-favicon.ico
  docs/_static/images/fairlearn-meta-image.jpg
  docs/_static/images/fairlearn_full_color.png
  docs/_static/images/fairlearn_full_white.png
  docs/_static/images/graphic-01.png
  docs/_static/images/graphic-02.png
  docs/_static/images/graphic-03.png
  docs/_static/images/graphic-04.png
  docs/_static/images/header-image.png
  docs/_static/images/icon-01-white.png
  docs/_static/images/icon-01.png
  docs/_static/images/icon-02-white.png
  docs/_static/images/icon-02.png
  docs/_static/images/icon-03-white.png
  docs/_static/images/icon-03.png
  docs/_static/images/icon-04-white.png
  docs/_static/images/icon-04.png
  docs/_static/images/icon-05-white.png
  docs/_static/images/icon-05.png
  docs/_static/images/icon-06-white.png
  docs/_static/images/icon-06.png
  docs/_static/images/icon-07-white.png
  docs/_static/images/icon-07.png
  docs/_static/images/main-graphic.png
  docs/_static/js/landing_page.js
  docs/_templates/index.html
  docs/conf.py
  docs/contents.rst
  docs/index.rst
  notebooks/Grid Search for Binary Classification.ipynb
Labels: documentation

#424 Added bound arguments to moments and implemented/updated unit tests accordingly
  AUTHORS.md
  fairlearn/reductions/_moments/bounded_group_loss.py
  fairlearn/reductions/_moments/conditional_selection_rate.py
  fairlearn/reductions/_moments/moment.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/exponentiated_gradient/test_lagrangian.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
  test/unit/reductions/moments/test_moments_bounded_group_loss.py
Labels: enhancement, feature-request
