Repository fairlearn/fairlearn, pull requests merged in 2020-01, with the labels that each got.

#219 Add more time metrics to performance tests
  fairlearn/reductions/_exponentiated_gradient/_exponentiated_gradient_result.py
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_grid_search/grid_search.py
  fairlearn/reductions/_grid_search/grid_search_result.py
  test/perf/script_generation.py
  test/perf/timed_execution.py
Labels: enhancement

#221 Fix perf tests by logging lists through log_list instead of log
  test/perf/script_generation.py
Labels: bug

#228 Perf tests: readability improvements & more metrics
  test/perf/metric_logging_script_expgrad_gridsearch.txt
  test/perf/metric_logging_script_postprocessing.txt
  test/perf/script_generation.py
Labels: enhancement

#251 Exclude install tests in code coverage check
  devops/templates/code-coverage-job-template.yml
  devops/templates/python-infra-upgrade-steps-template.yml
  requirements.txt
Labels: bug

#249 Replace powershell scripts with python and add Makefile
  CODEOWNERS.md
  CONTRIBUTING.md
  Makefile
  devops/templates/build-widget-job-template.yml
  devops/templates/create-wheel-step-template.yml
  scripts/_utils.py
  scripts/build-docs.ps1
  scripts/build-wheels.ps1
  scripts/build-widget.ps1
  scripts/build_wheels.py
  scripts/build_widget.py
  scripts/fairlearn_version.py
  scripts/process_readme.py
  scripts/set-variable-from-file.ps1
Labels: enhancement

#260 Fix pypi release yaml
  CONTRIBUTING.md
  devops/templates/build-widget-job-template.yml
  devops/templates/code-coverage-job-template.yml
  devops/templates/create-wheel-step-template.yml
  devops/templates/pypi-deployment-stages-template.yml
Labels: bug

#262 add CHANGES.md for v0.4.2
  CHANGES.md
  CONTRIBUTING.md
  fairlearn/__init__.py
  scripts/process_readme.py
  test/unit/reductions/grid_search/test_grid_search_regression.py
Labels: documentation

#267 Fix release blockers - widget generated files, widget validation
  devops/templates/build-widget-job-template.yml
  scripts/build_widget.py
Labels: bug

#272 remove --assert-no-changes flag in release as well
  devops/templates/create-wheel-step-template.yml
Labels: bug

#274 Fix build wheels script
  scripts/build_wheels.py
Labels: bug

#259 MNT use sklearn's NotFittedError instead of NotFittedException
  CHANGES.md
  fairlearn/exceptions.py
  fairlearn/postprocessing/_threshold_optimizer.py
  fairlearn/reductions/_grid_search/grid_search.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
Labels: enhancement

#276 DOC contributing: trim lines and add notes on signoff
  CONTRIBUTING.md
Labels: documentation
