Repository fairlearn/fairlearn, pull requests merged in 2020-04, with the labels that each got.

#358 Bump matplotlib to 3.2.1 and remove TkAgg workaround
  requirements.txt
  test/unit/postprocessing/test_plots.py
Labels: enhancement

#349 Unify inner state/results of ExponentiatedGradient and GridSearch
  CHANGES.md
  fairlearn/reductions/__init__.py
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  fairlearn/reductions/_grid_search/__init__.py
  fairlearn/reductions/_grid_search/_grid_generator.py
  fairlearn/reductions/_grid_search/grid_search.py
  fairlearn/reductions/_grid_search/grid_search_result.py
  notebooks/Binary Classification on COMPAS dataset.ipynb
  notebooks/Grid Search for Binary Classification.ipynb
  notebooks/Grid Search with Census Data.ipynb
  notebooks/Group Metrics.ipynb
  notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
  test/notebooks/test_notebooks.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/grid_search/test_grid_generator.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
  test/unit/reductions/grid_search/test_grid_search_demographicparity.py
  test/unit/reductions/grid_search/test_grid_search_regression.py
  test/unit/reductions/grid_search/utilities.py
Labels: enhancement, feature-request

#336 DOC move notebooks to sphinx user guides and generated docs
  .gitignore
  Makefile
  docs/conf.py
  docs/fairlearn.exceptions.rst
  docs/index.rst
  examples/README.rst
  examples/plot_binary_classification_COMPAS.py
  requirements.txt
  setup.cfg
Labels: documentation

#364 Addition of constraints
  .gitignore
  fairlearn/_input_validation.py
  fairlearn/reductions/__init__.py
  fairlearn/reductions/_moments/__init__.py
  fairlearn/reductions/_moments/conditional_selection_rate.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/moments/test_moments_demographic_parity.py
  test/unit/reductions/moments/test_moments_equalized_odds.py
Labels: enhancement

#374 Add Parul, Abdul, Kevin, and Stephanie to AUTHORS.md
  AUTHORS.md
Labels: documentation

#373 Pipeline Improvements
  devops/PR-Gate.yml
  devops/nightly-requirements-fixed.yml
  devops/nightly.yml
  devops/pypi-release.yml
  devops/templates/all-tests-job-template.yml
  devops/templates/fairlearn-installation-step-template.yml
  devops/templates/fetch-version-from-artifacts-steps-template.yml
  devops/templates/notebook-job-template.yml
  devops/templates/notebook-pypi-job-template.yml
  devops/templates/prepare-repo-for-pip-testing-steps-template.yml
  devops/templates/pypi-deployment-stages-template.yml
  devops/templates/unit-tests-pypi-job-template.yml
Labels: enhancement

#357 Update issue templates
  .github/ISSUE_TEMPLATE/blank_template.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc_improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/usage_question.md
  fairlearn/__init__.py
  fairlearn/show_versions.py
Labels: documentation

#337 UCI Credit Card Payment Default Demo
  notebooks/Binary Classification with the UCI Credit-card Default Dataset.ipynb
  requirements-3.5.txt
  requirements.txt
  test/notebooks/test_notebooks.py
Labels: enhancement

#378 update author link
  AUTHORS.md
Labels: documentation

#377 Enable GridSearch with more than 2 sensitive feature values
  CHANGES.md
  fairlearn/_input_validation.py
  fairlearn/reductions/_grid_search/_grid_generator.py
  fairlearn/reductions/_grid_search/grid_search.py
  test/unit/reductions/grid_search/test_grid_search_arguments.py
  test/unit/reductions/grid_search/utilities.py
  test/unit/reductions/test_smoke.py
Labels: feature-request

#329 Update communication guidelines in the repository
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#385 Remove usage questions template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/usage_question.md
Labels: documentation

#372 Add unit tests for exponentiated gradient
  fairlearn/reductions/_exponentiated_gradient/_lagrangian.py
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
  requirements-3.5.txt
  requirements.txt
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_arguments.py
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
  test/unit/reductions/exponentiated_gradient/test_lagrangian.py
  test/unit/reductions/exponentiated_gradient/test_utilities.py
Labels: enhancement

#396 Extend CircleCI workflow for GitHub pages deployment
  .circleci/config.yml
Labels: documentation

#402 restructuring docs for webpage according to doc proposal
  .circleci/config.yml
  docs/api_reference/fairlearn.metrics.rst
  docs/api_reference/fairlearn.postprocessing.rst
  docs/api_reference/fairlearn.reductions.rst
  docs/api_reference/fairlearn.widget.rst
  docs/api_reference/main.rst
  docs/community.rst
  docs/contribution_guide.rst
  docs/index.rst
  docs/quickstart.rst
  docs/user_guide/assessment.rst
  docs/user_guide/dashboard.rst
  docs/user_guide/exponentiated_gradient.rst
  docs/user_guide/fairness_in_machine_learning.rst
  docs/user_guide/grid_search.rst
  docs/user_guide/main.rst
  docs/user_guide/metrics.rst
  docs/user_guide/mitigation.rst
  docs/user_guide/postprocessing.rst
  docs/user_guide/reductions.rst
Labels: documentation
