Repository fairlearn/fairlearn, pull requests merged in 2020-06, with the labels that each got.

#445 [fairlearn dashboard] Support fluentUI theme
  visualization/FairnessDashboard/src/ChartColors.ts
  visualization/FairnessDashboard/src/Controls/AccuracyTab.styles.ts
  visualization/FairnessDashboard/src/Controls/AccuracyTab.tsx
  visualization/FairnessDashboard/src/Controls/BinDialog.styles.ts
  visualization/FairnessDashboard/src/Controls/BinDialog.tsx
  visualization/FairnessDashboard/src/Controls/DataSpecificationBlade.styles.ts
  visualization/FairnessDashboard/src/Controls/DataSpecificationBlade.tsx
  visualization/FairnessDashboard/src/Controls/FeatureTab.styles.ts
  visualization/FairnessDashboard/src/Controls/FeatureTab.tsx
  visualization/FairnessDashboard/src/Controls/IntroTab.styles.ts
  visualization/FairnessDashboard/src/Controls/IntroTab.tsx
  visualization/FairnessDashboard/src/Controls/ModelComparisionChart.styles.ts
  visualization/FairnessDashboard/src/Controls/ModelComparisonChart.tsx
  visualization/FairnessDashboard/src/Controls/SummaryTable.styles.ts
  visualization/FairnessDashboard/src/Controls/SummaryTable.tsx
  visualization/FairnessDashboard/src/Controls/TileList.styles.ts
  visualization/FairnessDashboard/src/Controls/TileList.tsx
  visualization/FairnessDashboard/src/Controls/WizardFooter.styles.ts
  visualization/FairnessDashboard/src/Controls/WizardFooter.tsx
  visualization/FairnessDashboard/src/FairnessWizard.styles.ts
  visualization/FairnessDashboard/src/FairnessWizard.tsx
  visualization/FairnessDashboard/src/Themes.ts
  visualization/FairnessDashboard/src/WizardReport.styles.ts
  visualization/FairnessDashboard/src/WizardReport.tsx
  visualization/test/test-page/App.jsx
Labels: enhancement

#446 Add F1 score and log loss
  fairlearn/metrics/_balanced_root_mean_squared_error.py
  fairlearn/metrics/_group_metric_set.py
  fairlearn/metrics/_metrics_engine.py
  fairlearn/widget/_fairlearn_dashboard.py
  fairlearn/widget/js/fairlearn_widget/labextension/fairlearn-widget-0.1.0.tgz
  notebooks/Binary Classification with the UCI Credit-card Default Dataset.ipynb
  test/unit/metrics/sample_dashboards/bc-1p-1f.json
  test/unit/metrics/sample_dashboards/bc-2p-3f.json
  test/unit/metrics/test_create_group_metric_set.py
  test/unit/metrics/test_group_sklearn_wrappers.py
  test/unit/metrics/test_metrics_engine_dicts.py
  visualization/FairnessDashboard/src/AccuracyMetrics.ts
  visualization/FairnessDashboard/src/Controls/ModelComparisonChart.tsx
  visualization/FairnessDashboard/src/Localization/en.json
  visualization/FairnessDashboard/src/WizardReport.tsx
  visualization/test/test-page/App.jsx
Labels: enhancement

#438 remove python 3.5 support
  devops/PR-Gate.yml
  devops/nightly.yml
  devops/pypi-release-new.yml
  devops/templates/all-tests-job-template.yml
  devops/templates/limited-installation-job-template.yml
  requirements-3.5.txt
  requirements.txt
  scripts/requirements_override.py
  setup.py
  test/unit/postprocessing/test_plots.py
Labels: dependencies

#454 Add adjusted structure for docs to accommodate roadmap, governance, and FAQ
  docs/about/index.rst
  docs/community/index.rst
  docs/contents.rst
  docs/contributor_guide/developer_call_notes/2020_05_07.rst
  docs/contributor_guide/developer_call_notes/index.rst
  docs/contributor_guide/index.rst
Labels: documentation

#461 add links to github from API reference
  docs/conf.py
Labels: documentation

#470 Document PR documentation requirements & numpydoc format switch
  docs/contributor_guide/development_process.rst
Labels: documentation

#450 add build_widget.py extension to build local changes
  scripts/build_widget.py
Labels: enhancement

#382 Document probabilistic classifier behavior in ExponentiatedGradient & calculate predictions only for non-zero weighted classifiers
  fairlearn/reductions/_exponentiated_gradient/exponentiated_gradient.py
Labels: documentation, enhancement

#426 Add fairness styleguide
  docs/contributor_guide/how_to_talk_about_fairness.rst
  docs/contributor_guide/index.rst
  docs/contributor_guide/ways_to_contribute.rst
Labels: documentation

#381 Add new constraints to ThresholdOptimizer and add InterpolatedThresholder
  CHANGES.md
  examples/notebooks/plot_binary_classification_COMPAS.py
  fairlearn/_input_validation.py
  fairlearn/postprocessing/_constants.py
  fairlearn/postprocessing/_interpolated_prediction.py
  fairlearn/postprocessing/_interpolated_thresholder.py
  fairlearn/postprocessing/_plotting.py
  fairlearn/postprocessing/_threshold_operation.py
  fairlearn/postprocessing/_threshold_optimizer.py
  fairlearn/postprocessing/_tradeoff_curve_utilities.py
  notebooks/Binary Classification on COMPAS dataset.ipynb
  test/install/test_no_matplotlib.py
  test/notebooks/test_notebooks.py
  test/unit/postprocessing/conftest.py
  test/unit/postprocessing/test_curve_utilities.py
  test/unit/postprocessing/test_plots.py
  test/unit/postprocessing/test_smoke.py
  test/unit/postprocessing/test_threshold_operation.py
  test/unit/postprocessing/test_threshold_optimization.py
Labels: enhancement

#479 Website: Change top navbar to link to documentation
  docs/_templates/index.html
Labels: documentation

#487 Quickstart update to avoid overfitting
  docs/quickstart.rst
  img/fairlearn-dashboard-comparison.png
  img/fairlearn-dashboard-disparity-performance.png
  img/fairlearn-dashboard-disparity-predictions.png
Labels: documentation

#451 Migrate metrics notebook content to user guide
  docs/conf.py
  docs/user_guide/assessment.rst
  docs/user_guide/mitigation.rst
  notebooks/Group Metrics.ipynb
  test/notebooks/test_notebooks.py
Labels: documentation

#481 Add developer call notes 06/11/2020
  docs/contributor_guide/developer_call_notes/2020_06_11.rst
  docs/contributor_guide/developer_call_notes/index.rst
Labels: documentation

#494 The Boston Dataset - Clean
  docs/api_reference/fairlearn.datasets.rst
  docs/api_reference/index.rst
  fairlearn/datasets/__init__.py
  fairlearn/datasets/_fetch_boston.py
  fairlearn/exceptions.py
Labels: enhancement
