Repository fairlearn/fairlearn, pull requests merged in 2021-05, with the labels that each got.

#763 Fix _merge_columns when using multiple sensitive features with long names
  CHANGES.md
  fairlearn/_input_validation.py
  test/unit/metrics/test_metricframe_smoke.py
  test/unit/postprocessing/test_threshold_optimizer_multiple_sensitive_features.py
Labels: bug

#760 Add updates to FAQ for multi class classification and multiple/non-binary sensitive features
  docs/faq.rst
  docs/user_guide/assessment.rst
  docs/user_guide/mitigation.rst
Labels: documentation

#767 Remove bokeh plot and replace with simple matplotlib plot
  docs/quickstart.rst
  docs/quickstart_plot.py
  examples/plot_quickstart_selection_rate.py
Labels: CI, dependencies

#775 Post-v0.6.2 release adjustments
  CHANGES.md
  README.md
  docs/contributor_guide/release.rst
  docs/static_landing_page/index.html
  fairlearn/__init__.py
Labels: documentation

#794 Update release instructions based on v0.6.2
  docs/contributor_guide/release.rst
Labels: documentation

#803 Migrate version upgrade guide for v0.3
  docs/contributor_guide/development_process.rst
  docs/user_guide/migrating_versions/index.rst
  docs/user_guide/migrating_versions/migrating_to_v0_3_0.rst
Labels: documentation

#770 Use matplotlib-based plots in documentation instead of FairlearnDashboard
  README.md
  docs/contributor_guide/contributing_example_notebooks.rst
  docs/contributor_guide/development_process.rst
  docs/quickstart.rst
  docs/user_guide/assessment.rst
  examples/plot_grid_search_census.py
  examples/plot_quickstart.py
  notebooks/Mitigating Disparities in Ranking from Binary Data.ipynb
  scripts/build_documentation.py
Labels: documentation

#807 Improve contributing_documention guide
  docs/contributor_guide/contributing_documentation.rst
Labels: documentation

#808 Add Twitter, StackOverflow, Gitter icons
  docs/_static/css/custom.css
  docs/conf.py
Labels: documentation
