Repository fairlearn/fairlearn, pull requests merged in 2021-07, with the labels that each got.

#883 FIX adjust test precision to 1e-5
  test/unit/reductions/exponentiated_gradient/test_exponentiatedgradient_smoke.py
Labels: CI, test

#885 MNT Convert README.md to README.rst
  CHANGES.md
  README.md
  README.rst
  docs/conf.py
  scripts/_utils.py
  scripts/build_wheels.py
  setup.py
Labels: documentation

#879 MNT update version references post v0.7.0 release
  CHANGES.md
  README.rst
  docs/conf.py
  docs/contributor_guide/release.rst
  docs/static_landing_page/index.html
  docs/static_landing_page/js/landing_page.js
  fairlearn/__init__.py
  requirements-dev.txt
Labels: documentation

#902 MNT pin sphinx at 4.0.3
  requirements-dev.txt
Labels: bug, documentation

#903 MNT remove gitpython, use git through subprocess instead
  docs/conf.py
  requirements-dev.txt
Labels: bug, dependencies, documentation

#905 MNT fix multiversion sphinx build
  docs/conf.py
  docs/contributor_guide/release.rst
Labels: bug, documentation

#904 Extend Migration Guide with Installation Guide
  AUTHORS.md
  docs/quickstart.rst
  docs/user_guide/index.rst
  docs/user_guide/installation_and_migration/index.rst
  docs/user_guide/installation_and_migration/installation_guide.rst
  docs/user_guide/installation_and_migration/migrating_to_v0_3_0.rst
  docs/user_guide/installation_and_migration/migrating_to_v0_5_0.rst
  docs/user_guide/installation_and_migration/migration_guide.rst
Labels: dependencies, documentation

#909 MNT add section for maintainers with avatars
  README.rst
  docs/_static/css/custom.css
  docs/about/index.rst
  scripts/build_documentation.py
  scripts/generate_maintainers_table.py
Labels: documentation

#913 FEAT add python 3.9 to setup.py
  CHANGES.md
  deps.txt
  devops/PR-Gate.yml
  devops/nightly-requirements-fixed.yml
  devops/templates/all-tests-job-template.yml
  setup.py
Labels: CI, dependencies

#912 DOC fix generation script path and add generated file
  docs/about/maintainers.rst
  docs/contributor_guide/release.rst
  scripts/build_documentation.py
Labels: CI, documentation

#893 DOC Add funding section to website
  docs/_static/css/custom.css
  docs/_static/images/anaconda.png
  docs/_static/images/microsoft.png
  docs/_static/images/tu_eindhoven.png
  docs/_static/images/zalando.png
  docs/about/index.rst
Labels: documentation
